### ISSUE TITLE
Error when building with Unity 5.5

### ISSUE THREAD

**Issue by spaggi2** [newyellow/Unity-Runtime-Animation-Recorder#4]
Hi,

first I'd like to let you know that this is fantastic!

However I'm having issues when Building with Unity 5.5. In editor.log, I get the following messagen:

Assets/3rd Party/Tools/Runtime Animation Recorder/UnityAnimSaver/UnityAnimationRecorder.cs(123,3): error CS0103: The name `AssetDatabase' does not exist in the current context

Thanks!

**Comment by newyellow** [comment]
Hi,

Because the AssetDatabase is one of UnityEditor's function, so it can't be import in the build.
I updated a small fix, which allows the building process, but the function will not working in the build.

I will try to find a replacement of AssetDatabase function in the future. But for now, you can't record into .anim in the build. If you really want to do the recording in the build, you can use the maya recorder though.

**Comment by spaggi2** [comment]
Awesome man, thank you so much. I wasn't sure this repo is still being maintained.

I don't need the function in the build, however would like to be able to build my project with you script imported.

Will try and close the issue if successful.

Thanks!

**Comment by newyellow** [comment]
haha you're welcome!
