### ISSUE TITLE
Could not find part of path

### ISSUE THREAD

**Issue by GingerHeadHouse** [newyellow/Unity-Runtime-Animation-Recorder#7]
Hello,  

I am getting an error in the console when attempting to export an animation to Maya:
DirectoryNotFoundException: Could not find a part of the path "C:\Users\...\REF_translateX_dataTemp"

I saw the suggestion on your YouTube channel on how to correct exporting a humanoid animation but I am still running to the issue on nodes that are only 3 characters long.  I am not certain on where to edit the recorder script either based on your second solution.  I am hoping to get a bit more info so I can get this working.  

Thank you!

**Comment by newyellow** [comment]
Thanks for the report! I found a bug and add a new option.

The bug occurs when recording nodes with parent. For example, record leftForeArm/leftArm/hand, the script will try to save a file named "leftForeArm/leftAmr/hand_dataTemp", but parents name will be treat as folders, and that cause the problem. And it's fixed now.

And I add an "Include Path Name" option. If every node's name in your model is unique, then you don't need this option checked.

Please update and try it. If it worked please let me know, and I will close this issue.

**Comment by GingerHeadHouse** [comment]
newyellow,

Thank you very much for the quick response and your efforts on this script.  Trying the updated version, I was able to complete an export without any errors.  The only issue however is that when viewing the .ma file in Maya afterwards, the animation is pretty jumbled.  The skeleton is quite unrecognizable as it distorts the skinned mesh.  

Here is the result:
[exportfile3.zip](https://github.com/newyellow/Unity-Runtime-Animation-Recorder/files/1312958/exportfile3.zip)

I've run through the triangle scene export and that works perfectly.  Fingers crossed, I hope there is a solution.  Thanks again!

**Comment by newyellow** [comment]
@GingerHeadHouse it seems the file doesn't have original model files. May I have the original model file without any animations?

**Comment by GingerHeadHouse** [comment]
Certainly, this is the default male character from the Autodesk Character Generator.
[DefaultMale_ExportToMaya.zip](https://github.com/newyellow/Unity-Runtime-Animation-Recorder/files/1314141/DefaultMale_ExportToMaya.zip)

**Comment by newyellow** [comment]
@GingerHeadHouse I've finally figured it out!

There were two problems cause the animation export not correct.

The first one is the rotation conversion. Unity's axis order is ZXY with left hand coordinate system, and Maya is XYZ and right hand coordinate. After hours of search I've finally found a correct way to convert it. (previous versions are wrong, but still works if the hierarchy is simple)

The second problem is the Joint Orientation setting difference. In Maya, there is an additional "Joint Orientation" value for all joints. But since Unity doesn't, this will cause problem. So you have to edit the model in Maya first, make all joints' "Joint Orientation" values to 0,0,0 (and copy the joint orientation values to it's transform's rotation, then the joint will remain the same rotation). And then you can use the exporter to export humanoid animation correctly. I've done some test and it worked well.

I will make a video tutorial about this process in these days, if the description is too poor, please wait for the video though : P

**Comment by newyellow** [comment]
@GingerHeadHouse I've recorded a video tutorial for it: [Unity Runtime Animation Recorder - Export Humanoid Animation to Maya](https://youtu.be/Ooxg-rFPTcM)
