### ISSUE TITLE
Demo Scene of Humanoid Animation Export?

### ISSUE THREAD

**Issue by GingerHeadHouse** [newyellow/Unity-Runtime-Animation-Recorder#8]
newyellow, any chance you could add a demo scene to show how this can successfully work?  I have been trying to get this working in a few different ways but my .ma file still keeps mangling the skeleton.  I believe I am using the most recent version after I saw the note about the script zeroing out the joint orient values.  I'm curious if I'm just doing one step wrong and am just not seeing it.  Would you be able to test out the original files I sent earlier to ensure it isn't a .ma file issue?  Could Maya 2018 be the issue?

Thanks for all the updates!

**Comment by newyellow** [comment]
There is no need to adjust the "Joint Orient" thing, now my script use RegExp to clear the problem.

The issue you have might caused by the positions. Since the recorder also records positions, if your model's scale in unity is not exactly the same as Maya, there will be problem.

I recorded a video for this, as you can see, the first result is odd. After changing the scale to 1, it exported nicely.
https://youtu.be/bA61HvhxbBo

The other way to deal with this, is to make the recorder don't record positions. Which can be done by script now, but I haven't offer an option in the inspector yet ... I'll add it today, since this is a very small change :p
